###

POST http://localhost:3001/api/customers/login
Content-Type: application/json

{
  "login": "alexsander11115@gmail.com" ,
  "password": "123456"
}

###
GET http://localhost:3001/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiY3VzdG9tZXJfaWQiOjEzMjgsImZpcnN0bmFtZSI6ItCc0LDQutGB0LjQvCIsImxhc3RuYW1lIjoi0JHQvtC90LTQsNGA0YwiLCJlbWFpbCI6InNhbGVzQHBldHouY29tLnVhIiwidGVsZXBob25lIjoiKzM4MDk3MjI1NTgxNCIsInBhc3N3b3JkIjoiNTYwNmE1ZDEyZDBkMTA2MDMwNTQyZWEzNzM2MmQ5N2Y2MjI3ZDRiNyIsInNhbHQiOiJZaWwzR1NacVciLCJzdGF0dXMiOnRydWV9LCJpYXQiOjE1NzI4Njg1MzEsImV4cCI6MTU3Mjg3MDMzMX0.Fl3DeMjpoQyxOle9CmxHf8b_lcGaqvr3NJEjtXrCfaA
###

###
PUT http://localhost:3001/api/customers/1328
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6MTMyOCwiZmlyc3RuYW1lIjoi0JzQsNC60YHQuNC8IiwibGFzdG5hbWUiOiLQkdC-0L3QtNCw0YDRjCIsImVtYWlsIjoic2FsZXNAcGV0ei5jb20udWEiLCJ0ZWxlcGhvbmUiOiIrMzgzODA5NjU4ODkyIiwicGFzc3dvcmQiOiJlZGU0NTMwYzRhOTNkYzgzMDNmZWIzZmRlOWI3M2M3YjIzMjVhOWQ4Iiwic2FsdCI6ImZWNVNKdmlHSiIsInN0YXR1cyI6dHJ1ZSwiaWF0IjoxNTczMzAyMjE3LCJleHAiOjE1NzMzMDQwMTd9.s6X3ppBV5nTlkxGT9gKA7LWkqTxURPY9S1fX1f_L_To
Content-Type: application/json

{
  "firstname": "Александр",
  "lastname": "Копыл",
  "email": "alexsander11115@gmail.com",
  "telephone": "+380630674453"
}
###

###
GET http://localhost:3001/api/customers/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiY3VzdG9tZXJfaWQiOjEzMjgsImZpcnN0bmFtZSI6ItCc0LDQutGB0LjQvCIsImxhc3RuYW1lIjoi0JHQvtC90LTQsNGA0YwiLCJlbWFpbCI6InNhbGVzQHBldHouY29tLnVhIiwidGVsZXBob25lIjoiKzM4MDk3MjI1NTgxNCIsInBhc3N3b3JkIjoiNTYwNmE1ZDEyZDBkMTA2MDMwNTQyZWEzNzM2MmQ5N2Y2MjI3ZDRiNyIsInNhbHQiOiJZaWwzR1NacVciLCJzdGF0dXMiOnRydWV9LCJpYXQiOjE1NzI4Njg1MzEsImV4cCI6MTU3Mjg3MDMzMX0.Fl3DeMjpoQyxOle9CmxHf8b_lcGaqvr3NJEjtXrCfaA
###

###
GET http://localhost:3001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6MTMyOCwiZmlyc3RuYW1lIjoi0JzQsNC60YHQuNC8IiwibGFzdG5hbWUiOiLQkdC-0L3QtNCw0YDRjCIsImVtYWlsIjoic2FsZXNAcGV0ei5jb20udWEiLCJ0ZWxlcGhvbmUiOiIrMzgwOTcyMjU1ODE0IiwicGFzc3dvcmQiOiI1NjA2YTVkMTJkMGQxMDYwMzA1NDJlYTM3MzYyZDk3ZjYyMjdkNGI3Iiwic2FsdCI6IllpbDNHU1pxVyIsInN0YXR1cyI6dHJ1ZSwiaWF0IjoxNTcyNjE3ODg3LCJleHAiOjE1NzI2MTk2ODd9.8JdJl1Q3OJT9UFo2imYxWBP6CfJBLWEI6AXr5FyRHTM

###

###
GET http://localhost:3001/api/orders/115
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6MTMyOCwiZmlyc3RuYW1lIjoi0JzQsNC60YHQuNC8IiwibGFzdG5hbWUiOiLQkdC-0L3QtNCw0YDRjCIsImVtYWlsIjoic2FsZXNAcGV0ei5jb20udWEiLCJ0ZWxlcGhvbmUiOiIrMzgwOTcyMjU1ODE0IiwicGFzc3dvcmQiOiI1NjA2YTVkMTJkMGQxMDYwMzA1NDJlYTM3MzYyZDk3ZjYyMjdkNGI3Iiwic2FsdCI6IllpbDNHU1pxVyIsInN0YXR1cyI6dHJ1ZSwiaWF0IjoxNTcyNjE3ODg3LCJleHAiOjE1NzI2MTk2ODd9.8JdJl1Q3OJT9UFo2imYxWBP6CfJBLWEI6AXr5FyRHTM

###
POST http://localhost:3001/api/customers/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiY3VzdG9tZXJfaWQiOjEzMjgsImZpcnN0bmFtZSI6ItCc0LDQutGB0LjQvCIsImxhc3RuYW1lIjoi0JHQvtC90LTQsNGA0YwiLCJlbWFpbCI6InNhbGVzQHBldHouY29tLnVhIiwidGVsZXBob25lIjoiKzM4MDk3MjI1NTgxNCIsInBhc3N3b3JkIjoiNTYwNmE1ZDEyZDBkMTA2MDMwNTQyZWEzNzM2MmQ5N2Y2MjI3ZDRiNyIsInNhbHQiOiJZaWwzR1NacVciLCJzdGF0dXMiOnRydWV9LCJpYXQiOjE1NzI1MzM4NjUsImV4cCI6MTU3MzEzODY2NX0.Kgpqjpufwn1raPA8bKO0iBhiIVgYaZiu1-mvw-1WMl8"
}

###